apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.configMap.namespace }}
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
{{ .Values.configMap.caBundle | indent 4 }}
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
{{- range .Values.configMap.registryMirrors }}
    [[registry]]
       prefix = ""
       location = "{{ .source }}"
       mirror-by-digest-only = true
       [[registry.mirror]]
       location = "{{ .mirror }}"
{{ end }}
